[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sprelf-pokemon-core"
version = "2026.08.02.0"
authors = [
    { name = "Christopher Dilley", email = "me@sprelf.com" }
]
description = "Core definitions for Pokémon entities"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dependencies = [
    "tree-format",
    "sprelf-json"
]
license = "GPL-3.0-only"
license-files = ["LICEN[SC]E.*"]

[project.urls]
repository = "https://github.com/cgdilley/EVHelperCore"

[tool.setuptools.packages.find]
where = ["src"]
include = ["SprelfPkmn*"]